{% set name = "ioproc" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ioproc-{{ version }}.tar.gz
  sha256: 39d46139322ea10e42ab2b19c92fa8994d52d0f1a0bcc4f1759ca220139f7191

build:
  entry_points:
    - ioproc = ioproc:run
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.8
    - cerberus >=1.3.4
    - pandas >=1.4.2
    - pyyaml >=6.0
    - pytables >=3.7.0
    - frozendict >=2.3.2
    - arrow >=1.2.2
    - click >=8.1.3
    - jinja2 >=3.1.2
    - attrs >=21.4.0
    - cattrs >=22.1.0
    - toml >=0.10.2

test:
  imports:
    - ioproc
  commands:
    - pip check
    - ioproc --help
  requires:
    - pip

about:
  home: https://gitlab.com/dlr-ve/ioproc
  summary: Workflow framework for data pre- and postprocessing.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - srmnitc
